// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day_10.Entities;

[Index("title1", Name = "titleind")]
public partial class title
{
    [Key]
    [StringLength(6)]
    [Unicode(false)]
    public string title_id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(80)]
    [Unicode(false)]
    public string title1 { get; set; }

    [Required]
    [StringLength(12)]
    [Unicode(false)]
    public string type { get; set; }

    [StringLength(4)]
    [Unicode(false)]
    public string pub_id { get; set; }

    [Column(TypeName = "money")]
    public decimal? price { get; set; }

    [Column(TypeName = "money")]
    public decimal? advance { get; set; }

    public int? royalty { get; set; }

    public int? ytd_sales { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string notes { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime pubdate { get; set; }

    [ForeignKey("pub_id")]
    [InverseProperty("titles")]
    public virtual publisher pub { get; set; }
}